# Generated by Django 5.1.5 on 2025-02-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
